version: "3.8"
services:
  elasticsearch:
    container_name: music-survey-elastic
    image: 'elasticsearch:8.7.0'
    volumes:
      - elastic:/data/db
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  postgres:
    container_name: music-survey-postgres
    image: 'postgres:alpine3.18'
    volumes:
      - postgres:/data/db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  music-survey-backend:
    container_name: music-survey-backend
    build: ./music-survey
    ports:
      - 8070:8070
    depends_on:
      - postgres
  music-survey-ingest:
    container_name: music-survey-ingest
    build: ./music-survey-ingest
    ports:
      - 8090:8090
    depends_on:
      - elasticsearch
      - music-survey-backend
  music-survey-frontend:
    container_name: music-survey-frontend
    build: ./music-survey-frontend
    ports:
      - 80:80
  jira:
    container_name: music-survey-jira
    image: 'atlassian/jira-software:latest'
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    ports:
      - 8000:8080
  confluence:
    container_name: music-survey-confluence
    image: 'atlassian/confluence:latest'
    volumes:
      - confluenceVolume:/var/atlassian/application-data/confluence
    ports:
      - 8010:8090
      - 8011:8091
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
    command: [ "start-dev" ]
    ports:
      - 8106:8080
    depends_on:
      - postgres
  pact-broker:
    image: pactfoundation/pact-broker
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact_broker
    ports:
      - 9292:9292
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: music-survey-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: music-survey-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: music-survey-kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
volumes:
  postgres:
  elastic:
  jiraVolume:
  confluenceVolume: